Fix TypeError: read_gld_csv() missing 1 required positional argument: 'rapportagetype'
Happened when runnning `brodata.gm.get_data_in_extent` or `brodata.gmw.get_data_in_extent` using `as_csv=True` and using `to_path` or `to_zip`.

Solves issue #51 and adds a test for this specific behaviour.